[env.production]
name = "pointage-app"
route = "pointage.example.com/*"
zone_id = ""  # Your Cloudflare zone ID

[site]
bucket = "./client/build"
entry-point = "workers-site"

[build]
command = "npm run build"
upload.format = "service-worker"
upload.dir = "client/build"

[env]
NODE_ENV = "production"

compatibility_date = "2023-05-18"
main = "index.js"
name = "pointage-workers-api"

# For Pages deployment
pages_build_output_dir = "client/build" 